-- =============================================================================
-- V3__create_inventory_transactions_table.sql
-- Create inventory_transactions table for tracking stock movements
-- =============================================================================

CREATE TABLE IF NOT EXISTS inventory_transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    quantity INTEGER NOT NULL,
    quantity_before INTEGER NOT NULL,
    quantity_after INTEGER NOT NULL,
    reason VARCHAR(255),
    reference_type VARCHAR(50),
    reference_id VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_inventory_transaction_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT chk_inventory_tx_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_inventory_tx_qty_before CHECK (quantity_before >= 0),
    CONSTRAINT chk_inventory_tx_qty_after CHECK (quantity_after >= 0)
);

CREATE INDEX IF NOT EXISTS idx_inventory_tx_product_id ON inventory_transactions (product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_tx_type ON inventory_transactions (transaction_type);
CREATE INDEX IF NOT EXISTS idx_inventory_tx_created_at ON inventory_transactions (created_at);
