-- =============================================================================
-- V4__create_suppliers_tables.sql
-- Create suppliers, supplier_phones, and supplier_emails tables
-- =============================================================================

-- Suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    gst_number VARCHAR(50),
    address VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Case-insensitive unique indexes on suppliers
CREATE UNIQUE INDEX IF NOT EXISTS uk_supplier_name_lower ON suppliers (LOWER(name));
CREATE UNIQUE INDEX IF NOT EXISTS uk_supplier_gst_number_lower ON suppliers (LOWER(gst_number));

-- Supplier phones table
CREATE TABLE IF NOT EXISTS supplier_phones (
    phone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    label VARCHAR(50),
    CONSTRAINT fk_supplier_phone_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_supplier_phone_supplier_id ON supplier_phones (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_phone_number ON supplier_phones (phone_number);

-- Supplier emails table
CREATE TABLE IF NOT EXISTS supplier_emails (
    email_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    email VARCHAR(100) NOT NULL,
    label VARCHAR(50),
    CONSTRAINT fk_supplier_email_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_supplier_email_supplier_id ON supplier_emails (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_email ON supplier_emails (email);
