-- =============================================================================
-- V5__create_purchase_management_tables.sql
-- Create purchases, purchase_items, purchase_payments, and purchase_sequences tables
-- Add last_purchase_price to products and movement_date to inventory_transactions
-- =============================================================================

-- 1. Alter products table to add last_purchase_price
ALTER TABLE products ADD COLUMN IF NOT EXISTS last_purchase_price NUMERIC(12, 2);

-- 2. Alter inventory_transactions table to add movement_date
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS movement_date DATE NOT NULL DEFAULT CURRENT_DATE;
CREATE INDEX IF NOT EXISTS idx_inventory_tx_movement_date ON inventory_transactions (movement_date);

-- 3. Sequence tracking table for yearly purchase numbers
CREATE TABLE IF NOT EXISTS purchase_sequences (
    year INTEGER PRIMARY KEY,
    last_value BIGINT NOT NULL DEFAULT 0
);

-- 4. Purchases table
CREATE TABLE IF NOT EXISTS purchases (
    purchase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_number VARCHAR(50) NOT NULL,
    supplier_id BIGINT NOT NULL,
    purchase_date DATE NOT NULL,
    invoice_number VARCHAR(100),
    invoice_date DATE,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount_percentage NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    tax_rate NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    tax_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    grand_total NUMERIC(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    notes VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_purchase_number UNIQUE (purchase_number),
    CONSTRAINT fk_purchase_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id) ON DELETE RESTRICT,
    CONSTRAINT chk_purchase_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_purchase_discount_amt CHECK (discount_amount >= 0),
    CONSTRAINT chk_purchase_tax_amt CHECK (tax_amount >= 0),
    CONSTRAINT chk_purchase_grand_total CHECK (grand_total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_purchases_supplier_id ON purchases (supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchases_purchase_date ON purchases (purchase_date);
CREATE INDEX IF NOT EXISTS idx_purchases_status ON purchases (status);

-- 5. Purchase Items table
CREATE TABLE IF NOT EXISTS purchase_items (
    purchase_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    purchase_price NUMERIC(12, 2) NOT NULL,
    item_total NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_purchase_item_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (purchase_id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_item_product FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE RESTRICT,
    CONSTRAINT uk_purchase_item_purchase_product UNIQUE (purchase_id, product_id),
    CONSTRAINT chk_purchase_item_quantity CHECK (quantity >= 1),
    CONSTRAINT chk_purchase_item_price CHECK (purchase_price >= 0),
    CONSTRAINT chk_purchase_item_total CHECK (item_total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase_id ON purchase_items (purchase_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_product_id ON purchase_items (product_id);

-- 6. Purchase Payments table
CREATE TABLE IF NOT EXISTS purchase_payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_reference VARCHAR(100),
    payment_date DATE NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_purchase_payment_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (purchase_id) ON DELETE RESTRICT,
    CONSTRAINT chk_purchase_payment_amount CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_purchase_payments_purchase_id ON purchase_payments (purchase_id);
CREATE INDEX IF NOT EXISTS idx_purchase_payments_date ON purchase_payments (payment_date);
