-- =============================================================================
-- V7__create_sales_management_tables.sql
-- Create sales, sale_items, sale_payments, sale_audit_history, and sale_sequences
-- =============================================================================

-- 1. Sequence tracking table for yearly sale numbers
CREATE TABLE IF NOT EXISTS sale_sequences (
    year INTEGER PRIMARY KEY,
    last_value BIGINT NOT NULL DEFAULT 0
);

-- 2. Sales table
CREATE TABLE IF NOT EXISTS sales (
    sale_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_number VARCHAR(50) NOT NULL,
    sale_date DATE NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount_percentage NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    grand_total NUMERIC(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    cancellation_reason VARCHAR(50),
    cancellation_description VARCHAR(500),
    cancelled_by VARCHAR(100),
    cancelled_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_sale_number UNIQUE (sale_number),
    CONSTRAINT chk_sale_status CHECK (status IN ('COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_sale_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_sale_discount_pct CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    CONSTRAINT chk_sale_discount_amt CHECK (discount_amount >= 0),
    CONSTRAINT chk_sale_grand_total CHECK (grand_total >= 0),
    CONSTRAINT chk_sale_cancellation_reason CHECK (
        cancellation_reason IS NULL OR cancellation_reason IN (
            'CUSTOMER_RETURNED_ITEM',
            'WRONG_SALE_ENTRY',
            'DUPLICATE_SALE',
            'BILLING_MISTAKE',
            'OTHER'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_sales_sale_date ON sales (sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_status ON sales (status);

-- 3. Sale Items table
CREATE TABLE IF NOT EXISTS sale_items (
    sale_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selling_price NUMERIC(12, 2) NOT NULL,
    item_total NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sales (sale_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sale_item_product FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_item_sale_product UNIQUE (sale_id, product_id),
    CONSTRAINT chk_sale_item_quantity CHECK (quantity >= 1),
    CONSTRAINT chk_sale_item_price CHECK (selling_price >= 0),
    CONSTRAINT chk_sale_item_total CHECK (item_total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON sale_items (product_id);

-- 4. Sale Payments table (exactly one payment per sale)
CREATE TABLE IF NOT EXISTS sale_payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30),
    description VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_sale_payment_sale FOREIGN KEY (sale_id) REFERENCES sales (sale_id) ON DELETE RESTRICT,
    CONSTRAINT uk_sale_payment_sale UNIQUE (sale_id),
    CONSTRAINT chk_sale_payment_amount CHECK (amount >= 0),
    CONSTRAINT chk_sale_payment_method CHECK (
        payment_method IS NULL OR payment_method IN (
            'CASH',
            'UPI',
            'CARD',
            'BANK_TRANSFER',
            'OTHER'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_sale_payments_sale_id ON sale_payments (sale_id);

-- 5. Sale Audit History table
CREATE TABLE IF NOT EXISTS sale_audit_history (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    user_id VARCHAR(100),
    action_type VARCHAR(30) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_sale_audit_sale FOREIGN KEY (sale_id) REFERENCES sales (sale_id) ON DELETE RESTRICT,
    CONSTRAINT chk_sale_audit_action CHECK (action_type IN ('SALE_CREATED', 'SALE_UPDATED', 'SALE_CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_sale_audit_sale_id ON sale_audit_history (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_audit_created_at ON sale_audit_history (created_at);
